homeassistant:
  name: Home Energy                    # Name shown in the Home Assistant UI
  latitude: !secret home_latitude     # Your location for sun-based automations (stored in secrets.yaml)
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric                 # Metric units (Celsius, meters, etc.)
  currency: SEK
  country: SE
  time_zone: Europe/Stockholm

modbus:
  - name: SMA
    type: tcp
    host: 192.168.10.100
    port: 502
    delay: 5
    timeout: 5
    message_wait_milliseconds: 200
    sensors:
      - name: SMA Instantaneous Power
        slave: 3
        address: 30775
        input_type: holding
        data_type: int32
        swap: word
        scale: 1
        precision: 0
        unit_of_measurement: "W"

      - name: SMA Total Energy
        slave: 3
        address: 30513
        input_type: holding
        data_type: uint64
        swap: word
        scale: 0.001
        precision: 3
        unit_of_measurement: "kWh"

      - name: SMA Current State of Health
        slave: 3
        address: 30201
        input_type: holding
        data_type: uint32
        swap: word
        unit_of_measurement: ""

template:
  - sensor:
      - name: Net Power Flow
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        icon: mdi:flash
        state: >
          {% set delivered = states('sensor.p1_dongle_pro_power_consumed') | default('0') | float(0) %}
          {% set returned = states('sensor.p1_dongle_pro_power_produced') | default('0') | float(0) %}
          {{ (delivered - returned) | round(1) }}

      - name: Estimated Self Consumption
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power
        icon: mdi:home-lightning-bolt-outline
        state: >
          {% set production = states('sensor.sma_instantaneous_power') | default('0') | float(0) %}
          {% set export = states('sensor.p1_dongle_pro_power_produced') | default('0') | float(0) %}
          {{ [production - export, 0] | max | round(1) }}

      - name: Solar Autonomy
        unit_of_measurement: "%"
        state_class: measurement
        device_class: battery
        icon: mdi:percent
        state: >
          {% set prod = states('sensor.sma_instantaneous_power') | default('0') | float(0) %}
          {% set import_ = states('sensor.p1_dongle_pro_power_consumed') | default('0') | float(0) %}
          {% set usage = prod + import_ %}
          {{ (prod / usage * 100) | round(1) if usage > 0 else 0 }}

mobile_app:
  push:
    ios:
      categories:
        - name: Home Energy
          identifier: home_energy
          actions:
            - identifier: view
              title: View
              activation_mode: background
              authentication_required: false
              destructive: false
              behavior: default
            - identifier: ignore
              title: Ignore
              activation_mode: background
              authentication_required: false
              destructive: true
              behavior: default
