homeassistant:
  name: Home Energy
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: SEK
  country: SE
  time_zone: Europe/Stockholm

# Modbus TCP integration to SMA inverter
modbus:
  - name: SMA
    type: tcp
    host: 192.168.10.100
    port: 502
    delay: 5         # Wait 5 seconds between Modbus queries (safe for inverter)
    timeout: 5       # Timeout if no response in 5s
    retries: 3       # Retry a few times if query fails
    sensors:
      - name: SMA Instantaneous Power
        slave: 3
        address: 30775
        input_type: holding
        data_type: uint16
        scale: 1
        precision: 0
        unit_of_measurement: "W"
