homeassistant:
  name: Home Energy                    # Name shown in the Home Assistant UI
  latitude: !secret home_latitude     # Your location for sun-based automations (stored in secrets.yaml)
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric                 # Metric units (Celsius, meters, etc.)
  currency: SEK
  country: SE
  time_zone: Europe/Stockholm

modbus:
  - name: SMA
    type: tcp
    host: 192.168.10.100
    port: 502
    delay: 5
    timeout: 5
    message_wait_milliseconds: 200
    sensors:
      - name: SMA Instantaneous Power
        slave: 3
        address: 30775
        input_type: holding
        data_type: int32
        scale: 1
        precision: 0
        unit_of_measurement: "W"
