esphome:
  name: atom-lite
  platform: ESP32
  board: m5stack-atom

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "AtomLite Fallback Hotspot"
    password: "fallbackpass123"

captive_portal:

logger:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

uart:
  rx_pin: GPIO3
  baud_rate: 9600

dsmr:
  id: dsmr_instance
  max_telegram_length: 1500

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Elförbrukning T1"
    energy_delivered_tariff2:
      name: "Elförbrukning T2"
    energy_returned_tariff1:
      name: "Elproduktion T1"
    energy_returned_tariff2:
      name: "Elproduktion T2"
    power_delivered:
      name: "Momentanförbrukning"
    power_returned:
      name: "Momentanproduktion"
    voltage_l1:
      name: "Spänning L1"
    current_l1:
      name: "Ström L1"
    power_delivered_l1:
      name: "Effekt köpt L1"
    power_returned_l1:
      name: "Effekt såld L1"
    instantaneous_power:
      name: "Total momentan effekt"
    voltage_sag_count:
      name: "Antal underspänningar"
    voltage_swell_count:
      name: "Antal överspänningar"

text_sensor:
  - platform: dsmr
    identification:
      name: "Mätar-ID"
    p1_version:
      name: "P1 Protokollversion"
    raw_telegram:
      name: "Råtelegram"
